FROM ubuntu:20.04
LABEL maintainer="Mike Townsley mike@madllama.net"

COPY grafana/ /etc/grafana/

# upgrade base packages
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y adduser libfontconfig1 wget

ARG GRAFANA_VERSION=grafana_6.7.3_amd64.deb
RUN cd /tmp && \
    wget https://dl.grafana.com/oss/release/${GRAFANA_VERSION} && \
    dpkg -i ${GRAFANA_VERSION}

WORKDIR /usr/share/grafana
