# configures a new raspberry pi
---

- name: Bring in some standard packages
  connection: local
  hosts: localhost
  tasks: 
  - name: Bring in VIM
    apt:
      name: vim
      state: present
    become: yes
    become_method: sudo

- name: Setup i2c
  connection: local
  hosts: localhost
  tasks: 
  - name: Update /boot/config.txt
    lineinfile:
      path: /boot/config.txt
      regexp: '^dtparam=i2c_arm'
      line: 'dtparam=i2c_arm=on'
    become: yes
    become_method: sudo

  - name: Update /etc/modules
    lineinfile:
      path: /etc/modules
      regexp: '^i2c-dev'
      line: 'i2c-dev'
    become: yes
    become_method: sudo

- name: Configure the watchdog timer
  connection: local
  hosts: localhost
  tasks: 
  - name: Update /boot/config.txt
    lineinfile:
      path: /boot/config.txt
      regexp: '^dtparam=watchdog'
      line: 'dtparam=watchdog=on'
    become: yes
    become_method: sudo

  - name: Install watchdog service
    apt:
      name: watchdog
      state: present
    become: yes
    become_method: sudo

  - name: Update watchdog timeout
    lineinfile:
      path: /etc/watchdog.conf
      regexp: '^watchdog-timeout'
      line: 'watchdog-timeout = 14'
    become: yes
    become_method: sudo

  - name: Update watchdog device
    lineinfile:
      path: /etc/watchdog.conf
      regexp: '^watchdog-device'
      line: 'watchdog-device = /dev/watchdog'
    become: yes
    become_method: sudo

  - name: Update watchdog interval
    lineinfile:
      path: /etc/watchdog.conf
      regexp: '^interval'
      line: 'interval = 5'
    become: yes
    become_method: sudo

  - name: Start the watchdog service
    systemd:
      name: watchdog
      enabled: yes
    become: yes
    become_method: sudo

- name: Install docker and docker-compose
  connection: local
  hosts: localhost
  tasks: 
  - name: Install docker package
    command: bash -c "curl -sSL https://get.docker.com | sh"
    args:
      creates: /usr/bin/docker
    become: yes
    become_method: sudo

  - name: Add pi to the docker group
    user:
      name: pi
      groups: docker
      append: yes
    become: yes
    become_method: sudo

  - name: Install dependencies
    apt:
      name: [libffi-dev,libssl-dev,python3,python3-pip]
      state: present
    become: yes
    become_method: sudo

  - name: Remove unwanted packages
    apt:
      name: python-configparser
      state: absent
    become: yes
    become_method: sudo

  - name: Use pip3 to bring in docker-compose
    pip:
      name: docker-compose
      executable: pip3
    become: yes
    become_method: sudo

- name: Setup rpt service 
  connection: local
  hosts: localhost
  tasks: 
  - name: Set the timezone
    timezone:
      name: America/Chicago
    become: yes
    become_method: sudo

  - name: Create postgress data directory
    file:
      path: /var/lib/postgresql/data
      state: directory
      mode: '0755'
      owner: pi
      group: pi
    become: yes
    become_method: sudo

  - name: Install the service configuration
    command: bash -c "cp /usr/local/rpt/etc/rpt.service /etc/systemd/system"
    args:
      creates: /etc/systemd/system/rpt.service
    become: yes
    become_method: sudo

  - name: Start the rpt service
    systemd:
      name: rpt
      enabled: yes
    become: yes
    become_method: sudo
