version: "3.7"
services:

  postgres:
    container_name: rpt-postgres
    labels: [rpt]
    image: ${HOSTTYPE_IMAGE_POSTGRES}
    environment:
      POSTGRES_USER: "rpt"
      POSTGRES_PASSWORD: "rpt"
      POSTGRES_DB: "rpt"
    volumes:
      - ./postgres:/var/lib/postgresql:delegated
    
  grafana:
    container_name: rpt-grafana
    labels: [rpt]
    image: ${HOSTTYPE_IMAGE_GRAFANA}
    environment:
      GF_PATHS_CONFIG: "/var/lib/grafana/grafana.ini"
    ports:
      - "3000:3000"
    user: "0"
    depends_on:
      - postgres
    volumes:
      - ./grafana:/var/lib/grafana:delegated

  rpt-daemon:
    build:
      args:
        HOSTTYPE: ${HOSTTYPE}
        HOSTTYPE_IMAGE: ${HOSTTYPE_IMAGE_RPT}
        NODEJS_VERSION: ${NODEJS_VERSION}
      context: ../
      dockerfile: ./docker/rpt/Dockerfile
    image: mbtown01/rpt:latest
    container_name: rpt-daemon
    labels: [rpt]
    privileged: true
    environment:
      TZ: ${TZ}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - grafana
    volumes:
      - ../:/usr/local/rpt
    entrypoint: ['python3', '-m', 'src', '--hardware', 'auto']

  rpt-term:
    build:
      args:
        HOSTTYPE: ${HOSTTYPE}
        HOSTTYPE_IMAGE: ${HOSTTYPE_IMAGE_RPT}
        NODEJS_VERSION: ${NODEJS_VERSION}
      context: ../
      dockerfile: ./docker/rpt/Dockerfile
    image: mbtown01/rpt:latest
    container_name: rpt-term
    labels: [rpt]
    privileged: true
    environment:
      TZ: ${TZ}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - grafana
    volumes:
      - ../:/usr/local/rpt
    entrypoint: ['python3', '-m', 'src', '--hardware', 'term']

  rpt-daemon-debug:
    build:
      args:
        HOSTTYPE: ${HOSTTYPE}
        HOSTTYPE_IMAGE: ${HOSTTYPE_IMAGE_RPT}
        NODEJS_VERSION: ${NODEJS_VERSION}
      context: ../
      dockerfile: ./docker/rpt/Dockerfile
    image: mbtown01/rpt:latest
    container_name: rpt-daemon-debug
    labels: [rpt]
    privileged: true
    environment:
      TZ: ${TZ}
    ports:
      - "5000:5000"
      - "3001:3001"
    depends_on:
      - postgres
      - grafana
    volumes:
      - ../:/usr/local/rpt
    entrypoint: ['python3', '-m', 'ptvsd',
      '--host', '0.0.0.0', '--port', '3001', '--wait', '-m', 'src',
      '--hardware', 'auto']

  rpt-term-debug:
    build:
      args:
        HOSTTYPE: ${HOSTTYPE}
        HOSTTYPE_IMAGE: ${HOSTTYPE_IMAGE_RPT}
        NODEJS_VERSION: ${NODEJS_VERSION}
      context: ../
      dockerfile: ./docker/rpt/Dockerfile
    image: mbtown01/rpt:latest
    container_name: rpt-term-debug
    labels: [rpt]
    privileged: true
    environment:
      TZ: ${TZ}
    ports:
      - "5000:5000"
      - "3001:3001"
    depends_on:
      - postgres
      - grafana
    volumes:
      - ../:/usr/local/rpt
    entrypoint: ['python3', '-m', 'ptvsd',
      '--host', '0.0.0.0', '--port', '3001', '--wait', '-m', 'src',
      '--hardware', 'term']

  rpt-dev:
    build:
      args:
        HOSTTYPE: ${HOSTTYPE}
        HOSTTYPE_IMAGE: ${HOSTTYPE_IMAGE_RPT}
        NODEJS_VERSION: ${NODEJS_VERSION}
      context: ../
      dockerfile: ./docker/rpt/Dockerfile
    image: mbtown01/rpt:latest
    container_name: rpt-dev
    labels: [rpt]
    privileged: true
    environment:
      TZ: ${TZ}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - grafana
    volumes:
      - ../:/usr/local/rpt
    entrypoint: ['bash', '-c', 'while sleep 600; do /bin/false; done']
