version: "3.7"

x-frosti-2: &frosti-defaults
  labels: [frosti]
  privileged: true
  ports:
    - "5000:5000"
  environment:
    LC_ALL: C
  depends_on:
    - postgres
    - grafana

services:
  postgres:
    container_name: frosti-postgres
    labels: [frosti]
    image: arm32v6/postgres:12.2-alpine
    environment:
      POSTGRES_USER: "frosti"
      POSTGRES_PASSWORD: "frosti"
      POSTGRES_DB: "frosti"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated

  grafana:
    image: mbtowns/grafana:arm-latest
    build:
      context: .
      dockerfile: ./grafana/Dockerfile.arm
    container_name: frosti-grafana
    labels: [frosti]
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - grafana-data:/var/lib/grafana:delegated
      - ./grafana:/etc/grafana:delegated

  frosti-daemon:
    <<: *frosti-defaults
    image: mbtowns/frosti:arm-latest
    build:
      context: .
      dockerfile: ./frosti/Dockerfile.arm
    container_name: frosti-daemon
    volumes:
      - ../:/usr/local/frosti:delegated
    entrypoint: ["python3", "-m", "frosti", "--hardware", "auto"]

  frosti-dev:
    <<: *frosti-defaults
    image: mbtowns/frosti-dev:arm-latest
    build:
      context: .
      dockerfile: ./frosti/Dockerfile.arm
      args:
        FROSTI_DEV: "true"
    container_name: frosti-dev
    volumes:
      - ../:/usr/local/frosti:delegated
    entrypoint: ["bash", "-c", "while sleep 600; do /bin/false; done"]

volumes:
  postgres-data:
    external: true
  grafana-data:
    external: true
