version: "3.7"
services:

  influxdb:
    container_name: rpt-influxdb
    build:
      args:
        HOSTTYPE_IMAGE: ${HOSTTYPE_IMAGE_INFLUX}
      context: ../
      dockerfile: ./docker/influxdb/Dockerfile
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      INFLUXDB_ADMIN_USER: "rpt"
      INFLUXDB_ADMIN_PASSWORD: "rpt"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    volumes:
      - type: volume
        source: influxdb
        target: /var/lib/influxdb

  grafana:
    container_name: rpt-grafana
    image: ${HOSTTYPE_IMAGE_GRAFANA}
    ports:
      - "3000:3000"
    user: "0"
    depends_on:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana:delegated

  rpt:
    build:
      args:
        HOSTTYPE: ${HOSTTYPE}
        HOSTTYPE_IMAGE: ${HOSTTYPE_IMAGE_RPT}
      context: ../
      dockerfile: ./docker/rpt/Dockerfile
    container_name: rpt
    privileged: true
    ports:
      - "5000:5000"
    depends_on:
      - influxdb
      - grafana
    volumes:
      - ../:/usr/local/rpt

volumes:
  influxdb:
