version: "3.7"
services:

  postgres:
    container_name: rpt-postgres
    labels: [rpt]
    image: "postgres:12.2"
    environment:
      POSTGRES_PASSWORD: "rpt"
      POSTGRES_DB: "rpt"
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql

  grafana:
    container_name: rpt-grafana
    labels: [rpt]
    image: ${HOSTTYPE_IMAGE_GRAFANA}
    ports:
      - "3000:3000"
    user: "0"
    depends_on:
      - postgres
    volumes:
      - ./grafana:/var/lib/grafana:delegated

  rpt:
    build:
      args:
        HOSTTYPE: ${HOSTTYPE}
        HOSTTYPE_IMAGE: ${HOSTTYPE_IMAGE_RPT}
        NODEJS_VERSION: ${NODEJS_VERSION}
      context: ../
      dockerfile: ./docker/rpt/Dockerfile
    container_name: rpt
    labels: [rpt]
    privileged: true
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - grafana
    volumes:
      - ../:/usr/local/rpt

volumes:
  postgres:
