version: "3.7"

x-rpt-defaults:
  &rpt-defaults
  labels: [rpt]
  privileged: true
  ports:
    - "5000:5000"
  environment:
    LC_ALL: C
  depends_on:
    - postgres
    - grafana

services:

  postgres:
    container_name: rpt-postgres
    labels: [rpt]
    image: postgres:12.2
    environment:
      POSTGRES_USER: "rpt"
      POSTGRES_PASSWORD: "rpt"
      POSTGRES_DB: "rpt"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  grafana:
    image: mbtowns/grafana:x86_64-latest
    build:
      context: grafana/
      dockerfile: ./Dockerfile.x86_64
    container_name: rpt-grafana
    labels: [rpt]
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - grafana-data:/usr/local/grafana
      - ./grafana/plugins:/etc/grafana/plugins

  rpt-daemon:
    <<: *rpt-defaults
    image: mbtowns/rpt:x86_64-latest
    build:
      context: rpt/
      dockerfile: ./Dockerfile.x86_64
    container_name: rpt-daemon
    entrypoint: ['python3', '-m', 'src', '--hardware', 'term']

  rpt-dev:
    <<: *rpt-defaults
    image: mbtowns/rpt-dev:x86_64-latest
    build:
      context: rpt/
      dockerfile: ./Dockerfile.x86_64
      args:
        RPT_DEV: 'true'
    container_name: rpt-dev
    volumes:
      - ../:/usr/local/rpt
    entrypoint: ['bash', '-c', 'while sleep 600; do /bin/false; done']

volumes:
  postgres-data:
    external: true
  grafana-data:
    external: true