# docker-compose --file docker/develop.yaml build
# docker-compose --file docker/develop.yaml run rpt
# For running rpt directly and docker/grafana in the container
# docker-compose --file docker/develop.yaml rup
# screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
# docker volume inspect docker_grafana
# docker volume inspect docker_influxdb
# docker-compose --file


version: "3.7"
services:

  influxdb:
    image: influxdb:latest
    container_name: rpt-influxdb
    build:
      context: ../
      dockerfile: ./docker/influxdb/Dockerfile
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      INFLUXDB_ADMIN_USER: "rpt"
      INFLUXDB_ADMIN_PASSWORD: "rpt"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    volumes:
      - type: volume
        source: influxdb
        target: /var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: rpt-grafana
    ports:
      - "3000:3000"
    user: "0"
    depends_on:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana:delegated

  rpt:
    image: rpt/develop:latest
    build:
      context: ../
      dockerfile: ./docker/rpt/Dockerfile
    container_name: rpt
    ports:
      - "5000:5000"
    depends_on:
      - influxdb
      - grafana
    volumes:
      - ../:/usr/local/rpt

volumes:
  influxdb: