{
 "title": "Overview",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Currently",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature\nFROM sensor_reading\nORDER BY 1 DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Power Price",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"time\",\n  price AS \"price\"\nFROM griddy_update\nORDER BY 1 DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"time\",\n  humidity AS \"humidity\"\nFROM sensor_reading\nORDER BY 1 DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  comfort_max AS \"Cooling Target\"\nFROM thermostat_targets\nORDER BY 1 DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  comfort_min AS \"Heating Target\"\nFROM thermostat_targets\nORDER BY 1 DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Temperature vs Targets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "farenheit", "label": "Temperature" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(temperature) AS \"temperature\"\nFROM sensor_reading\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(humidity) AS \"humidity\"\nFROM sensor_reading\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "select\n  $__timeGroupAlias(bar.time,$__interval,previous),\n  max(bar.comfort_max) AS \"comfort_max\"    \nfrom (\n    select\n        time,\n        last_value(comfort_max)\n        over (\n            partition by floor(extract(epoch from time)/60)*60\n            order by time\n            range between unbounded preceding and unbounded following\n        ) comfort_max\n    from\n        thermostat_targets\n    union\n    select\n        $__timeFrom() as time,\n        last_value(comfort_max)\n        over (\n            order by time\n            range between unbounded preceding and unbounded following\n        ) comfort_max\n    from\n        thermostat_targets\n    WHERE\n        \"time\" < $__timeFrom()\n) bar\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "select\n  $__timeGroupAlias(bar.time,$__interval,previous),\n  max(bar.comfort_min) AS \"comfort_min\"    \nfrom (\n    select\n        time,\n        last_value(comfort_min)\n        over (\n            partition by floor(extract(epoch from time)/60)*60\n            order by time\n            range between unbounded preceding and unbounded following\n        ) comfort_min\n    from\n        thermostat_targets\n    union\n    select\n        $__timeFrom() as time,\n        last_value(comfort_min)\n        over (\n            order by time\n            range between unbounded preceding and unbounded following\n        ) comfort_min\n    from\n        thermostat_targets\n    WHERE\n        \"time\" < $__timeFrom()\n) bar\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Run History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval,previous),\n  max(cooling) AS \"cooling\"\nFROM thermostat_state\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval,previous),\n  max(heating) AS \"heating\"\nFROM thermostat_state\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Power Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "currencyUSD", "label": "$/kW*hr" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(price) AS \"price\"\nFROM griddy_update\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "type": "madllama-net-rpt-control-panel", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 } },
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    min(foo.time) as time, avg(foo.delta)/60.0 as \"average cycle time\"\nfrom (\n    select\n        time, 1 as group,\n        lag(cooling) over (order by time) as lastCooling,\n        lag(heating) over (order by time) as lastHeating,\n        extract(epoch from time-lag(time) over (order by time)) as delta\n    from thermostat_state\n    ) as foo\nwhere\n  $__timeFilter(foo.time)\n  and lastCooling + lastHeating > 0\ngroup by\n  foo.group"
    },
    {
     "rawSql": "select\n    min(foo.time) as time, min(foo.delta)/60.0 as \"minimum cycle time\"\nfrom (\n    select\n        time, 1 as group,\n        lag(cooling) over (order by time) as lastCooling,\n        lag(heating) over (order by time) as lastHeating,\n        extract(epoch from time-lag(time) over (order by time)) as delta\n    from thermostat_state\n    ) as foo\nwhere\n  $__timeFilter(foo.time)\n  and lastCooling + lastHeating > 0\ngroup by\n  foo.group"
    },
    {
     "rawSql": "select\n    min(foo.time) as time, max(foo.delta)/60.0 as \"maximun cycle time\"\nfrom (\n    select\n        time, 1 as group,\n        lag(cooling) over (order by time) as lastCooling,\n        lag(heating) over (order by time) as lastHeating,\n        extract(epoch from time-lag(time) over (order by time)) as delta\n    from thermostat_state\n    ) as foo\nwhere\n  $__timeFilter(foo.time)\n  and lastCooling + lastHeating > 0\ngroup by\n  foo.group"
    }
   ]
  }
 ]
}