@startuml ObjectRelationalModel

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "OrmThermostat" as thermostat {
  *uid : integer <<generated>>
  --
  *name : text
}

entity "OrmGriddyConfig" as griddyConfig {
  *uid : integer <<generated>>
  --
  *meter_id : string
  *thermostat_uid : integer <<FK>>
  --
}
thermostat ||..o| griddyConfig

entity "OrmGriddyUpdate" as griddyUpdate {
  *griddy_config_uid: integer <<FK>>
  *time: datetime
  --
  price: float
}
griddyConfig ||..o{ griddyUpdate

entity "OrmProgram" as program {
  *uid : integer <<generated>>
  --
  *name: string
  *thermostat_uid : integer <<FK>>
  --
  comfort_min: float
  comfort_max: float
}
thermostat ||..o{ program

entity "OrmPriceOverride" as priceOverrides {
  *thermostat_uid : integer <<FK>>
  *program_uid: integer <<FK>>
  --
  comfort_min: float
  comfort_max: float
}
thermostat ||..o{ priceOverrides

entity "OrmSchedule" as schedule {
  *thermostat_uid : integer <<FK>>
  *day: integer
  *hour: integer
  *minute: integer
  --
  *program_name: string <<FK>>
}
thermostat ||..o{ schedule
program ||..o{ schedule


entity "OrmSensorReading" as sensorReading {
  *thermostat_uid : integer <<FK>>
  *time: datetime
  --
  temperature: float
  pressure: float
  humidity: float
}
thermostat ||..o{ sensorReading

entity "OrmThermostatState" as thermostatState {
  *thermostat_uid : integer <<FK>>
  *time: datetime
  --
  fan: integer
  cooling: integer
  heating: integer
}
thermostat ||..o{ thermostatState


entity "OrmThermostatTargets" as thermostatTargets {
  *thermostat_uid : integer <<FK>>
  *time: datetime
  --
  mode: integer
  comfort_min: float
  comfort_max: float
}
thermostat ||..o{ thermostatTargets


@enduml