@startuml ObjectRelationalModel

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

frame "Programming" {
  entity "OrmProgram" as program {
    *name: string
    --
    comfort_min: float
    comfort_max: float
  }

  entity "OrmPriceOverride" as price_overrides {
    *program_name: string <<FK>>
    *price: float
    --
    comfort_min: float
    comfort_max: float
  }
  program ||..o{ price_overrides

  entity "OrmSchedule" as schedule {
    *name: string
  }

  entity "OrmScheduleDay" as schedule_day {
    *day: integer
    --
    schedule_name: string <<FK>>
  }
  schedule ||..o{ schedule_day

  entity "OrmScheduleTime" as schedule_time {
    *schedule_name: string <<FK>>
    *hour: integer
    *minute: integer
    --
    program_name: string <<FK>>
  }
  schedule ||..o{ schedule_time
  program ||..o{ schedule_time
}

frame "State Capture" {
  entity "OrmThermostatTargets" as thermostat_targets {
    *time: datetime
    --
    mode: integer
    comfort_min: float
    comfort_max: float
  }

  entity "OrmSensorReading" as sensor_reading {
    *time: datetime
    --
    temperature: float
    pressure: float
    humidity: float
  }

  entity "OrmThermostatState" as thermostat_state {
    *time: datetime
    --
    fan: boolean
    cooling: boolean
    heating: boolean
  }

  entity "OrmGriddyUpdate" as griddy_update {
    *time: datetime
    --
    price: float
  }
}

frame "Configuration" {
  entity "OrmConfig" as config {
    *name: string
    --
    value: string
  }
}

@enduml